### ISSUE TITLE
ReportServer Exception

### ISSUE THREAD

**Issue by steves714** [Microsoft/Reporting-Services#137]
I'm not sure what's missing and have reviewed my setup and everything appears to be correct. When I try and browse to reportserver this exception is thrown. Does anybody have an idea on what i could be missing?

webserver!ReportServer_0-1!2998!02/01/2019-10:31:30:: e ERROR: Throwing Microsoft.ReportingServices.Diagnostics.Utilities.UnhandledHttpApplicationException: , Microsoft.ReportingServices.Diagnostics.Utilities.UnhandledHttpApplicationException: The report server encountered an unhandled exception in HttpApplication. ---> System.NullReferenceException: Object reference not set to an instance of an object.
   at Microsoft.ReportingServices.Library.WebConfigUtil.GetWebConfigAuthenticationNode()
   at Microsoft.ReportingServices.Library.WebConfigUtil.<>c__DisplayClass1.<GetWebConfigAuthenticationAttribute>b__0()
   at Microsoft.ReportingServices.Diagnostics.RevertImpersonationContext.<>c__DisplayClass1.<Run>b__0(Object state)
   at System.Security.SecurityContext.Run(SecurityContext securityContext, ContextCallback callback, Object state)
   at Microsoft.ReportingServices.Diagnostics.RevertImpersonationContext.Run(ContextBody callback)
   at Microsoft.ReportingServices.Library.WebConfigUtil.GetWebConfigAuthenticationAttribute(String attrName)
   at Microsoft.ReportingServices.Library.WebConfigUtil.GetAuthenticationType()
   at Microsoft.ReportingServices.Library.WebConfigUtil.get_WebServerAuthMode()
   at Microsoft.ReportingServices.Library.WebConfigUtil.get_UsingFormsAuth()
   at Microsoft.ReportingServices.WebServer.Global.FormsAuthentication_OnAuthenticate(Object sender, FormsAuthenticationEventArgs e)
   at System.Web.Security.FormsAuthenticationModule.OnAuthenticate(FormsAuthenticationEventArgs e)
   at System.Web.Security.FormsAuthenticationModule.OnEnter(Object source, EventArgs eventArgs)
   at System.Web.HttpApplication.SyncEventExecutionStep.System.Web.HttpApplication.IExecutionStep.Execute()
   at System.Web.HttpApplication.ExecuteStepImpl(IExecutionStep step)
   at System.Web.HttpApplication.ExecuteStep(IExecutionStep step, Boolean& completedSynchronously)
   --- End of inner exception stack trace ---;

**Comment by steves714** [comment]
Restored the 3 config files back to their original state and windows auth works fine. Gone through setting it up multiple times and everything is configured according to the documentation but continue to getting this exception.

NullReferenceException at 
Microsoft.ReportingServices.Library.WebConfigUtil.GetWebConfigAuthenticationNode() line 107

**Comment by jtarquino** [comment]
For initial setup I recommend to use a clean default environment of PBIRS and run the automatic configuration of the sample https://github.com/Microsoft/Reporting-Services/tree/master/CustomSecuritySample#automatic-configuration-of-the-sample

**Comment by steves714** [comment]
All the steps are automated in a PowerShell Script, if you have a Power BI Report Server default installation you can run (the script is only valid for Power BI Report Server, for SSRS you need to follow the manual steps)

This is SSRS.

**Comment by steves714** [comment]
In case anybody ever runs into this issue, it turns out that I had installed the latest version of SSRS2017 (October Release) and updated the original install of SSRS2017. Had to uninstall SSRS and reinstall a clean copy of the latest version and now custom auth is working.
