### ISSUE TITLE
 Could not load file or assembly 'Microsoft.ReportingServices.Interfaces, Version=2019.5.0.0,

### ISSUE THREAD

**Issue by jcf0419** [microsoft/Reporting-Services#152]
having an issue with Microsoft.ReportingServices.Interfaces on deploy.

I cloned the repo and built using visual studio 2019.
After deploying and restarting the service via the instruction in the read.me
The URL of the report server returns 503.

Below: was pulled from RSPowerBI log after starting Power BI Report Server using configuration manager.

2019-08-02 14:36:40.6400|ERROR|1|Error loading extension: 
System.IO.FileLoadException: Could not load file or assembly 'Microsoft.ReportingServices.Interfaces, Version=2019.5.0.0, Culture=neutral, PublicKeyToken=89845dcd8080cc91' or one of its dependencies. The located assembly's manifest definition does not match the assembly reference. (Exception from HRESULT: 0x80131040)
File name: 'Microsoft.ReportingServices.Interfaces, Version=2019.5.0.0, Culture=neutral, PublicKeyToken=89845dcd8080cc91'
   at System.Reflection.RuntimeAssembly.GetType(RuntimeAssembly assembly, String name, Boolean throwOnError, Boolean ignoreCase, ObjectHandleOnStack type)
   at System.Reflection.RuntimeAssembly.GetType(String name, Boolean throwOnError, Boolean ignoreCase)
   at System.Reflection.Assembly.CreateInstance(String typeName, Boolean ignoreCase, BindingFlags bindingAttr, Binder binder, Object[] args, CultureInfo culture, Object[] activationAttributes)
   at Microsoft.BIServer.Owin.Common.Services.AuthExtensionProvider.CreateExtensionObject(Extension extConfig, Boolean typeOnly)

Please help is possible.

**Comment by gboreki** [comment]
This could be related to differences of the interfaces version of your build machine and the production or test server. The version you built against was from May/2019, what is the version of the server you are running it?
