### ISSUE TITLE
ERROR: Unhandled exception: System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation. ---> System.Net.HttpListenerException: Access is denied

### ISSUE THREAD

**Issue by srini-morapaka** [microsoft/Reporting-Services#164]
I have a issue as below while accessing SSRS reports. I am able access web service, but while accessing portal like http://localhost:8787/Reports throwing error and response in browser is below.

Not Found

HTTP Error 404. The requested resource is not found.

ERROR: Unhandled exception: System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation. ---> System.Net.HttpListenerException: Access is denied
   at System.Net.HttpListener.AddAllPrefixes()
   at System.Net.HttpListener.Start()
   at Microsoft.Owin.Host.HttpListener.OwinHttpListener.Start(HttpListener listener, Func`2 appFunc, IList`1 addresses, IDictionary`2 capabilities, Func`2 loggerFactory)
   at Microsoft.Owin.Host.HttpListener.OwinServerFactory.Create(Func`2 app, IDictionary`2 properties)
   --- End of inner exception stack trace ---
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor)
   at System.Reflection.RuntimeMethodInfo.UnsafeInvokeInternal(Object obj, Object[] parameters, Object[] arguments)
   at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at Microsoft.Owin.Hosting.ServerFactory.ServerFactoryAdapter.Create(IAppBuilder builder)
   at Microsoft.Owin.Hosting.Engine.HostingEngine.Start(StartContext context)
   at Microsoft.ReportingServices.Portal.WebHost.Services.Impl.WebAppWrapper.Start(StartOptions options, IPortalConfigurationManager rsConfigManager, ILogger logger)
   at Microsoft.ReportingServices.Portal.WebHost.Services.Impl.WebAppServiceController.Start()
   at Microsoft.ReportingServices.Portal.WebHost.Program.Run()
   at Microsoft.ReportingServices.Portal.WebHost.Program.Main(String[] args).

can anyone has solution or suggestion please.

**Comment by jtarquino** [comment]
I would recommend to post your question in the https://social.msdn.microsoft.com/Forums/sqlserver/en-US/home?forum=sqlreportingservices so the community can help you or contact support.
This project only covers questions about the samples

**Comment by srini-morapaka** [comment]
Thanks, I resolved the issue by uninstalling and reinstalling the SSRS.
