### ISSUE TITLE
Sample for SSRS 2019 Forms authentication ?

### ISSUE THREAD

**Issue by ststeiger** [microsoft/Reporting-Services#208]
I'm trying to get Forms-Authentication working in SSRS 2019. 
Previous version where I got it to work was SSRS 2012. 

As I implemented FormsAuthentication_RS2019, I see it requires framework 4.6.2. 
Is that correct ? 

All I get is:
```
The service is not available. 
The report server has encountered a configuration error. 
```
And that is not particularly helpful. 

All that's in the logfiles is 
```
2020-11-17 10:22:00.4809|INFO|14|Deleting expired log file: C:\Program Files\Microsoft SQL Server Reporting Services\SSRS\LogFiles\RSPortal_2020_10_30_15_04_03.log Last written: 30.10.2020 15:04:03
2020-11-17 10:22:00.4809|WARN|14|Exception deleting expired log fileSystem.IO.IOException: The process cannot access the file 'C:\Program Files\Microsoft SQL Server Reporting Services\SSRS\LogFiles\RSPortal_2020_10_30_15_04_03.log' because it is being used by another process.
   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.File.InternalDelete(String path, Boolean checkHost)
   at Microsoft.BIServer.HostingEnvironment.Logger.DeleteExpiredFilesInternal(Int32 keepUntilDays, FileInfo[] logFiles)
```
 and that isn't particularly helpful, especially as RSPortal_2020_10_30_15_04_03.log is not opened by a user process...

**Comment by ststeiger** [comment]
Never mind, figured it out myslefs.
