### ISSUE TITLE
The permissions granted to "username" are insufficient to perform this operation. (rsAccessDenied)

### ISSUE THREAD

**Issue by itcrowder** [microsoft/Reporting-Services#224]
It looks like I did everything according to the instructions. But I have a problem. 

I register a new **testuser** (this function works fine), then I try to log in as **testuser**. If I enter the password incorrectly, then the **http://myservername/rootfoldername/logon.aspx** page is updated over and over again (there are no problems with this part of the code either)
But if I specify the **correct password**, then authentication is **successful**, the request is redirected to the **http://myservername/rootfoldername/default.aspx** page (which I do not see in the _<install>_ directory at file system), and there I get this message
**The permissions granted to "testuser" are insufficient to perform this operation. (rsAccessDenied)**

A snippet of HTML code of the error page generated in my browser:

```
<meta name="HTTP Status" content="500" />
<meta name="ProductLocaleID" content="127" />
<meta name="CountryLocaleID" content="1049" />
<meta name="StackTrace" content="   at Microsoft.ReportingServices.Library.GetItemTypeAction.PerformActionNow()
   at Microsoft.ReportingServices.Library.RSSoapAction`1.Execute()
   at Microsoft.ReportingServices.WebServer.Global.IsRequestForReport()
   at Microsoft.ReportingServices.WebServer.Global.IsViewerNeeded()
   at Microsoft.ReportingServices.WebServer.Global.DispatchRequest()
   at Microsoft.ReportingServices.WebServer.Global.Application_AuthenticateRequest(Object sender, EventArgs e)" />
<style>
```

It looks like the problem is in this line of code:
```
            if (passwordVerified)
            {
                
               FormsAuthentication.RedirectFromLoginPage(TxtUser.Text, false);

                }
```
If I understand correctly, custom Forms authentication and authorization completes successfully (passwordVerified = true), then it redirects to main page of the report server, but SSRS tries to authorize **testuser** again with its internal algorithm. And it fails because **testuser** is not in the list of SSRS users. But **testuser** can't be there because it's not even a domain account. **testuser** only exists in the **[UserAccounts]. [Dbo]. [Users]** table.

**And I cannot understand how can I tell my report server that the authorization procedure has already been passed in the current session?**

**Comment by itcrowder** [comment]
Solwes! Porblem in RSReportServer.config file: 
```
        <Configuration>
          <AdminConfiguration>
            <UserName>username</UserName>
          </AdminConfiguration>
        </Configuration>
```
In UserName tag must be **testuser** (in my case )
