### ISSUE TITLE
Exception of type 'System.Web.HttpUnhandledException' was thrown.  Index was outside the bounds of the array.  

### ISSUE THREAD

**Issue by eneerge** [microsoft/Reporting-Services#231]
I just compiled the CustomSecuritySample2016 and deployed it to a remote SSRS server. It redirects to logon.aspx and then dumps an error: **index outside the bounds of the array.**

![image](https://user-images.githubusercontent.com/7434613/125522207-a4cad1a2-cb7a-4d6c-85eb-dd161663c944.png)

Looking at the logs, I can see the full stack trace:

`webserver!ReportServer_0-1!17f8!07/13/2021-15:38:31:: e ERROR: Throwing Microsoft.ReportingServices.Diagnostics.Utilities.UnhandledHttpApplicationException: , Microsoft.ReportingServices.Diagnostics.Utilities.UnhandledHttpApplicationException: The report server encountered an unhandled exception in HttpApplication. ---> System.Web.HttpUnhandledException: Exception of type 'System.Web.HttpUnhandledException' was thrown. ---> System.IndexOutOfRangeException: Index was outside the bounds of the array.
   at System.Web.Configuration.MachineKeySection.SetInnerOuterKeys(Byte[] validationKey, Byte[]& inner, Byte[]& outer)
   at System.Web.Configuration.MachineKeySection.ConfigureEncryptionObject()
   at System.Web.Configuration.MachineKeySection.EnsureConfig()
   at System.Web.Configuration.MachineKeySection.GetEncodedData(Byte[] buf, Byte[] modifier, Int32 start, Int32& length)
   at System.Web.UI.ObjectStateFormatter.Serialize(Object stateGraph, Purpose purpose)
   at System.Web.UI.Util.SerializeWithAssert(IStateFormatter2 formatter, Object stateGraph, Purpose purpose)
   at System.Web.UI.HiddenFieldPageStatePersister.Save()
   at System.Web.UI.Page.SaveAllState()
   at System.Web.UI.Page.ProcessRequestMain(Boolean includeStagesBeforeAsyncPoint, Boolean includeStagesAfterAsyncPoint)
   --- End of inner exception stack trace ---
   at System.Web.UI.Page.HandleError(Exception e)
   at System.Web.UI.Page.ProcessRequestMain(Boolean includeStagesBeforeAsyncPoint, Boolean includeStagesAfterAsyncPoint)
   at System.Web.UI.Page.ProcessRequest(Boolean includeStagesBeforeAsyncPoint, Boolean includeStagesAfterAsyncPoint)
   at System.Web.UI.Page.ProcessRequest()
   at System.Web.UI.Page.ProcessRequest(HttpContext context)
   at System.Web.HttpApplication.CallHandlerExecutionStep.System.Web.HttpApplication.IExecutionStep.Execute()
   at System.Web.HttpApplication.ExecuteStepImpl(IExecutionStep step)
   at System.Web.HttpApplication.ExecuteStep(IExecutionStep step, Boolean& completedSynchronously)
   --- End of inner exception stack trace ---;`

It looks like it has something to do with the MachineKey. I used Powershell script shown at the bottom of this page to generate the machineKey configuration: https://support.microsoft.com/en-us/topic/resolving-view-state-message-authentication-code-mac-errors-6c0e9fd3-f8a8-c953-8fbe-ce840446a9f3#appendixa . I also tried passing in "sha1" as a parameter to the function just to see if that would help, but it did not.

I ran the powershell script on the server that the DLL is being deployed to as well as the development machine to no avail.

Does anyone know what else can be tried?

**Comment by eneerge** [comment]
This is embarrassing.

The issue was the Powershell script on the link I posted adds a line break in the middle of the machineKey output. I thought VS was just word wrapping, but there was a line break in the MachineKey output. I have it working after removing the line break.

**Comment by moqueet009** [comment]
having same issue can u help me.
