### ISSUE TITLE
Can't upload PBIX File.

### ISSUE THREAD

**Issue by hideaki2007** [Microsoft/Reporting-Services#30]
I configured custom authentication in Power BI Report Server.
But when i upload .pbix file, it throws an error.
( .rdl files and excel files can be uploaded successfully) 

The log file (RSPowerBI.log) contains the following information.

```
2017-07-18 03:36:34.9195|ERROR|7|Unhandled Exception in the owin pipeline ExceptionSystem.NullReferenceException: Object reference not set to an instance of an object.
   at Microsoft.BIServer.Owin.Common.Services.AuthenticationService.GetUserInfo(RsRequestContext requestContext)
   at Microsoft.BIServer.Owin.Common.CustomAuthenticationMiddleware.Invoke(IOwinContext context)
   at Microsoft.BIServer.Owin.Common.GlobalExceptionHandlerMiddleware.<Invoke>d__0.MoveNext()
2017-07-18 03:36:45.6086|INFO|7|Dump result: External dump process return code 0x20000001.
External dump process returned no errors.
.
```

**Comment by parthsha** [comment]
Have you copied your CustomSecurity.dll to the PowerBI folder?

**Comment by hideaki2007** [comment]
Thanks ,Parthsha.

After I copied CustomSecurity.dll and CustomSecurity.pdb to the PowerBI folder, I successed to  upload PBI files.

**Comment by longnv6** [comment]
How to fix : {"error":{"code":"102","message":"There was an error uploading your .pbix file.  Verify that the file has not been corrupted and that the file extension matches the format of the file."}}, when upload .pbix file into power bi reports server (9/2021). I use Power BI Desktop (9/2021) to create pbix file
