### ISSUE TITLE
System.NotSupportedException: PortalIdentity is not supported

### ISSUE THREAD

**Issue by alpersogukpinar** [Microsoft/Reporting-Services#34]
Hi,
I am using Power BI Report Server - 14.0.600.301
I can see RDL reports (http://localhost/reports/report/Test) while using custom security extension, but when I try to open a power bi report (http://localhost/reports/powerbi/MyUserReport), I get an exception like “System.NotSupportedException: PortalIdentity is not supported”.

**RSPowerBI.log**

> 2017-08-03 11:35:16.8710|ERROR|90|Failure in conceptualschema| RequestID = 5a55046e-0305-361b-e214-71fd8b0d79ff ClientSessionID = 3aee7b14-c24b-d6ac-237d-38809550b1bb System.NotSupportedException: PortalIdentity is not supported.
>    at Microsoft.PowerBI.ReportServer.ExploreHost.UserIdentityConnectionImpersonatorFactory.CreateImpersonator(IIdentity identity)
>    at Microsoft.PowerBI.ReportServer.ExploreHost.RSPowerViewHandler.GetModelInfo(String id)
>    at System.Lazy`1.CreateValue()
>    at System.Lazy`1.LazyInitValue()
>    at Microsoft.PowerBI.ReportServer.ExploreHost.RSModelCache.GetOrAddModel(ModelKey key, Func`1 modelInfoFunc)
>    at Microsoft.PowerBI.ReportServer.ExploreHost.RSPowerViewHandler.EnsureSession(String modelId)
>    at Microsoft.PowerBI.ExploreHost.ExploreClientHandlerBaseFlow.<RunAsync>b__8_0()
>    at System.Threading.Tasks.Task.Execute()
> --- End of stack trace from previous location where exception was thrown ---
>    at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
>    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
>    at Microsoft.PowerBI.ExploreHost.ExploreClient.<GetClientConceptualSchemaAsync>d__10.MoveNext()
> --- End of stack trace from previous location where exception was thrown ---
>    at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
>    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
>    at Microsoft.PowerBI.ReportServer.ExploreHost.RSExploreHost.<GetConceptualSchemaAsync>d__4.MoveNext()
> --- End of stack trace from previous location where exception was thrown ---
>    at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
>    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
>    at Microsoft.PowerBI.ReportServer.WebApi.PbiApi.PbiApiController.<GetConceptualSchemaAsync>d__6.MoveNext()

**Comment by alpersogukpinar** [comment]
Problem solved with @parthsha 's help.

This was due to the data source attempting to use integrated security which is not supported with custom Auth. When I editted the data source for the report and used stored credentials, It worked. Please find attached screenshot for the change.
![sil](https://user-images.githubusercontent.com/8727187/28957224-ab5e4924-78f9-11e7-8e52-e8831dc18e5f.jpg)
