### ISSUE TITLE
Error after login (The report server has encountered a configuration error. (rsServerConfigurationError))

### ISSUE THREAD

**Issue by tuananhti** [Microsoft/Reporting-Services#39]
Hi All, I am try custom authen on power bi report server, but after I login, I had error (The report server has encountered a configuration error. (rsServerConfigurationError)).

I Do not  know how fixed this error. can Someone help me

![untitled](https://user-images.githubusercontent.com/1570038/29744081-6220bb54-8ac7-11e7-9790-d42c33a09a33.png)
![untitled1](https://user-images.githubusercontent.com/1570038/29744086-6a674350-8ac7-11e7-9757-f9ba243ec50c.png)

**this event log**
![untitled2](https://user-images.githubusercontent.com/1570038/29748163-191dfa56-8b3b-11e7-875b-080fca826776.png)

**Comment by tuananhti** [comment]
**And I run portal, in log file by**
RSPortal!reportserverwebapp!RSPortal.exe!3!08/27/2017-15:44:37:: e ERROR:  fe80::9577:fb4f:e7e2:5586%12: GET  - 0:00:00.0960627
Exception: System.Web.HttpException (0x80004005): Unable to validate data.
   at System.Web.Configuration.MachineKeySection.EncryptOrDecryptData(Boolean fEncrypt, Byte[] buf, Byte[] modifier, Int32 start, Int32 length, Boolean useValidationSymAlgo, Boolean useLegacyMode, IVType ivType, Boolean signData)
   at System.Web.Security.FormsAuthentication.Decrypt(String encryptedTicket)
   at Microsoft.ReportingServices.Portal.WebHost.Common.RsRequestContext.get_User()
   at LVReportingServiceExtension.AuthenticationExtension.GetUserInfo(IRSRequestContext requestContext, IIdentity& userIdentity, IntPtr& userId)
   at Microsoft.ReportingServices.Portal.WebHost.Services.AuthenticationService.GetUserInfo(RsRequestContext requestContext)
   at Microsoft.ReportingServices.Portal.WebHost.Owin.CustomAuthenticationMiddleware.Invoke(IOwinContext context)
   at Microsoft.Owin.Security.Infrastructure.AuthenticationMiddleware`1.<Invoke>d__0.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.ReportingServices.Portal.WebHost.Owin.RequestLoggingMiddleware.<Invoke>d__0.MoveNext() | RequestID = s_73204c0c-c5c9-4ed1-b91d-7f3d7ab4d96a

**Comment by sneevand** [comment]
How did you resolve it?
