### ISSUE TITLE
Report name mismatch and Could not load Authorization extension

### ISSUE THREAD

**Issue by martindlarsson** [Microsoft/Reporting-Services#57]
I have implemented Custom Security following the guide in [https://github.com/Microsoft/Reporting-Services/tree/master/CustomSecuritySample](https://github.com/Microsoft/Reporting-Services/tree/master/CustomSecuritySample).
I am able to register a user and login but once the page for the portal starts to load I get en error message:
The service is not available.
The report server has encountered a configuration error.
[Learn more](https://go.microsoft.com/fwlink/?linkid=847142)

In the log file i found this:
```
RSPortal!extensionfactory!RSPortal.exe!7!11/17/2017-14:30:22:: e ERROR: Exception caught instantiating Forms report server extension: System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation. ---> System.TypeInitializationException: The type initializer for 'Microsoft.Samples.ReportingServices.CustomSecurity.Authorization' threw an exception. ---> System.Exception: Report name mismatch
   at Microsoft.Samples.ReportingServices.CustomSecurity.Authorization.InitializeMaps() in C:\Users\mala56\OneDrive - Landstinget i Värmland\Portalen\Autentisering\CustomSecuritySample\Authorization.cs:line 576
   at Microsoft.Samples.ReportingServices.CustomSecurity.Authorization..cctor() in C:\Users\mala56\OneDrive - Landstinget i Värmland\Portalen\Autentisering\CustomSecuritySample\Authorization.cs:line 42
   --- End of inner exception stack trace ---
   at Microsoft.Samples.ReportingServices.CustomSecurity.Authorization..ctor()
   --- End of inner exception stack trace ---
   at System.RuntimeTypeHandle.CreateInstance(RuntimeType type, Boolean publicOnly, Boolean noCheck, Boolean& canBeCached, RuntimeMethodHandleInternal& ctor, Boolean& bNeedSecurityCheck)
   at System.RuntimeType.CreateInstanceSlow(Boolean publicOnly, Boolean skipCheckThis, Boolean fillCache, StackCrawlMark& stackMark)
   at System.RuntimeType.CreateInstanceDefaultCtor(Boolean publicOnly, Boolean skipCheckThis, Boolean fillCache, StackCrawlMark& stackMark)
   at System.Activator.CreateInstance(Type type, Boolean nonPublic)
   at System.RuntimeType.CreateInstanceImpl(BindingFlags bindingAttr, Binder binder, Object[] args, CultureInfo culture, Object[] activationAttributes, StackCrawlMark& stackMark)
   at System.Activator.CreateInstance(Type type, BindingFlags bindingAttr, Binder binder, Object[] args, CultureInfo culture, Object[] activationAttributes)
   at System.Reflection.Assembly.CreateInstance(String typeName, Boolean ignoreCase, BindingFlags bindingAttr, Binder binder, Object[] args, CultureInfo culture, Object[] activationAttributes)
   at Microsoft.ReportingServices.Diagnostics.ExtensionClassFactory.<>c__DisplayClass2.<CreateExtensionObject>b__0()
   at Microsoft.ReportingServices.Diagnostics.RevertImpersonationContext.<>c__DisplayClass1.<Run>b__0(Object state)
   at System.Security.SecurityContext.Run(SecurityContext securityContext, ContextCallback callback, Object state)
   at Microsoft.ReportingServices.Diagnostics.RevertImpersonationContext.Run(ContextBody callback)
   at Microsoft.ReportingServices.Diagnostics.ExtensionClassFactory.CreateExtensionObject(Extension extConfig, Boolean typeOnly).
RSPortal!library!RSPortal.exe!7!11/17/2017-14:30:22:: e ERROR: Throwing Microsoft.ReportingServices.Diagnostics.Utilities.ServerConfigurationErrorException: Could not load Authorization extension, Microsoft.ReportingServices.Diagnostics.Utilities.ServerConfigurationErrorException: The report server has encountered a configuration error. ;
RSPortal!reportserverwebapp!RSPortal.exe!7!11/17/2017-14:30:23:: e ERROR: OData exception occurred: Microsoft.ReportingServices.Diagnostics.Utilities.ServerConfigurationErrorException: The report server has encountered a configuration error. 
   at Microsoft.ReportingServices.Library.Security.get_AuthorizationExtension()
   at Microsoft.ReportingServices.Library.Security.<>c__DisplayClassd.<GetSystemPermissions>b__b()
   at Microsoft.ReportingServices.Diagnostics.ExtensionBoundary.Invoke(Method m)
   at Microsoft.ReportingServices.Library.Security.GetSystemPermissions()
   at Microsoft.ReportingServices.Library.GetSystemPermissionsAction.PerformActionNow()
   at Microsoft.ReportingServices.Library.RSSoapAction`1.Execute()
   at Microsoft.ReportingServices.Portal.Repositories.SystemService.GetAllowedSystemActions(IPrincipal userPrincipal)
   at Microsoft.ReportingServices.Portal.ODataWebApi.V2.Controllers.UnboundFunctionController.ServiceState()
   at lambda_method(Closure , Object , Object[] )
   at System.Web.Http.Controllers.ReflectedHttpActionDescriptor.ActionExecutor.<>c__DisplayClass10.<GetExecutor>b__9(Object instance, Object[] methodParameters)
   at System.Web.Http.Controllers.ReflectedHttpActionDescriptor.ExecuteAsync(HttpControllerContext controllerContext, IDictionary`2 arguments, CancellationToken cancellationToken)
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at System.Web.Http.Controllers.ApiControllerActionInvoker.<InvokeActionAsyncCore>d__0.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at System.Web.Http.Controllers.ActionFilterResult.<ExecuteAsync>d__2.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at System.Web.Http.Controllers.ExceptionFilterResult.<ExecuteAsync>d__0.MoveNext(). | RequestID = s_407cc314-12e8-4449-b080-3ed81b84826c
```

I am positive that I have not made any mistakes in the configuration and the code is unchanged.

**Comment by martindlarsson** [comment]
I think I know why I get this error. When building the solution I got some compile errors in Authorization.cs on lines 567, 568, 583 and 584. I am missing some enums it seems:

```
ReportOperation.Comment
ReportOperation.ManageComments
```

And in the class OperationNames I am missing `OperComment` and `OperManageComments`

I commented out these lines and then I get above error.

In ReportOperation and OperationNames the comment says `Assembly Microsoft.ReportingServices.Interfaces, Version=13.0.0.0`. This is from adding the dll from Nuget package managed by Microsoft.

When I instead copied the Microsoft.ReportingServices.Interfaces.dll from C:\Program Files\Microsoft Power BI Report Server\PBIRS\PowerBI from the server and ad it as a reference, it says version 14 instead and I no longer have compile errors.

This solves my problem but I urge you to add instructions on how to add reference to the correct dll in Visual Studio.
