### ISSUE TITLE
Question for soap access

### ISSUE THREAD

**Issue by winglo** [Microsoft/Reporting-Services#58]
I am able to customized the project "CustomSecuritySample2016" that use Postgres DB for verifying username and password. And I can login to the SSRS on the login page.

Now I need to communicate to the SSRS from a JAVA application with the use of SOAP.  And I have the following exception. Is it caused by the custom authentication?

```
com.sun.xml.internal.ws.client.ClientTransportException: The server sent HTTP status code 500: Server Error
	at com.sun.xml.internal.ws.transport.http.client.HttpTransportPipe.createResponsePacket(HttpTransportPipe.java:266)
	at com.sun.xml.internal.ws.transport.http.client.HttpTransportPipe.process(HttpTransportPipe.java:217)
	at com.sun.xml.internal.ws.transport.http.client.HttpTransportPipe.processRequest(HttpTransportPipe.java:130)
	at com.sun.xml.internal.ws.transport.DeferredTransportPipe.processRequest(DeferredTransportPipe.java:95)
	at com.sun.xml.internal.ws.api.pipe.Fiber.__doRun(Fiber.java:1121)
	at com.sun.xml.internal.ws.api.pipe.Fiber._doRun(Fiber.java:1035)
	at com.sun.xml.internal.ws.api.pipe.Fiber.doRun(Fiber.java:1004)
	at com.sun.xml.internal.ws.api.pipe.Fiber.runSync(Fiber.java:862)
	at com.sun.xml.internal.ws.client.Stub.process(Stub.java:448)
	at com.sun.xml.internal.ws.client.sei.SEIStub.doProcess(SEIStub.java:178)
	at com.sun.xml.internal.ws.client.sei.SyncMethodHandler.invoke(SyncMethodHandler.java:93)
	at com.sun.xml.internal.ws.client.sei.SyncMethodHandler.invoke(SyncMethodHandler.java:77)
	at com.sun.xml.internal.ws.client.sei.SEIStub.invoke(SEIStub.java:147)
	at com.sun.proxy.$Proxy215.getPermissions(Unknown Source)
```

**Comment by jt000** [comment]
It is possible something isn't configured right in the CustomSecuritySample2016 project. To get more info, I'd suggest debugging into the CustomSecuritySample2016 project or add logging to the project to get more information on what failed (exception, stack trace, etc.)
