### ISSUE TITLE
Custom Authentication for SSRS2017

### ISSUE THREAD

**Issue by SLazaroc** [Microsoft/Reporting-Services#71]
Hi, I'm trying to configure a Custom Authentication for SSRS 2017. I followed the instructions on this sample for SSRS 2016.  However It seem that it just doesn't work for SSRS 2017, this is the error it get when try to authenticate the user on Web Portal:

> <Header>
  <Product>Microsoft SQL Server Reporting Services Version 14.0.600.451</Product>
  <Locale>en-US</Locale>
  <TimeZone>Pacific Standard Time</TimeZone>
  <Path>C:\Program Files\Microsoft SQL Server Reporting Services\SSRS\LogFiles\RSPortal_2018_03_02_19_30_05.log</Path>
  <SystemName>[MY_COMPUTER_NAME]</SystemName>
  <OSName>Microsoft Windows NT 6.2.9200.0</OSName>
  <OSVersion>6.2.9200.0</OSVersion>
</Header>
RSPortal!reportserverwebapp!RSPortal.exe!1!03/02/2018-19:30:05:: i INFO: Starting ReportServerWebApp
RSPortal!reportserverwebapp!RSPortal.exe!1!03/02/2018-19:30:05:: i INFO: Working directory : C:\Program Files\Microsoft SQL Server Reporting Services\SSRS\Portal
RSPortal!reportserverwebapp!RSPortal.exe!1!03/02/2018-19:30:05:: i INFO: Report Server url: http://[MY_COMPUTER_NAME]/ReportServer_SSRS
RSPortal!reportserverwebapp!RSPortal.exe!1!03/02/2018-19:30:05:: i INFO: Report Server Web App virtual root: /Reports_SSRS
RSPortal!reportserverwebapp!RSPortal.exe!1!03/02/2018-19:30:05:: i INFO: Web app url: http://+:80/Reports_SSRS/
RSPortal!reportserverwebapp!RSPortal.exe!1!03/02/2018-19:30:05:: i INFO: Authentication scheme(s): Anonymous
RSPortal!crypto!RSPortal.exe!1!03/02/2018-19:30:07:: i INFO: Initializing crypto as user: NT SERVICE\SQLServerReportingServices
RSPortal!crypto!RSPortal.exe!1!03/02/2018-19:30:07:: i INFO: Exporting public key
RSPortal!crypto!RSPortal.exe!1!03/02/2018-19:30:07:: i INFO: Importing existing encryption key
RSPortal!reportserverwebapp!RSPortal.exe!3!03/02/2018-19:30:12:: i INFO: Received request GET  | RequestID = s_3c7ba74e-99bb-41cc-979c-6b482fb3e390 
RSPortal!reportserverwebapp!RSPortal.exe!3!03/02/2018-19:30:12:: e ERROR:  fe80::1c94:e697:e660:78b3%12: GET  - 0:00:00.0548553
Exception: System.Web.HttpException (0x80004005): Unable to validate data.
   at System.Web.Configuration.MachineKeySection.EncryptOrDecryptData(Boolean fEncrypt, Byte[] buf, Byte[] modifier, Int32 start, Int32 length, Boolean useValidationSymAlgo, Boolean useLegacyMode, IVType ivType, Boolean signData)
   at System.Web.Security.FormsAuthentication.Decrypt(String encryptedTicket)
   at Microsoft.BIServer.Owin.Common.Middleware.CustomAuthenticationMiddleware.CreateRequestContextFromCookie(IOwinContext context)
   at Microsoft.BIServer.Owin.Common.Middleware.CustomAuthenticationMiddleware.CreatePortalIdentity(IOwinContext context)
   at Microsoft.BIServer.Owin.Common.Middleware.CustomAuthenticationMiddleware.Invoke(IOwinContext context)
   at Microsoft.Owin.Security.Infrastructure.AuthenticationMiddleware`1.<Invoke>d__0.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.BIServer.Owin.Common.Middleware.RequestLoggingMiddleWare.<Invoke>d__2.MoveNext() | RequestID = s_3c7ba74e-99bb-41cc-979c-6b482fb3e390 

Any help would be appreciated.

**Comment by ganeshmahajan1985** [comment]
Hi @SLazaroc , did you found any solution ?
I am also stuck on the same issue.
Also one more thing i do not understand about this documentation, it gives API sample for sql server 2017 rest API, but no custom extension for 2017.

**Comment by ganeshmahajan1985** [comment]
Hi @jtarquino ,
as per your suggestion I followed the link and did the needful, but still it is not working. 
- Also only server url working, for portal it is still showing 503 error.
- On server URL if we click register button nothing happens. 
Could you help please ? Am I missing something ? or the documentation has missing part?

**Comment by jtarquino** [comment]
You will need to check the logs to see the error, they are located on C:\Program Files\Microsoft Power BI Report Server\PBIRS\LogFiles\RSPortal_*.log

**Comment by SLazaroc** [comment]
hello @ganeshmahajan1985 after followed the instructions for SSRS 2016 custom authentication in [CustomSecuritySample2016](https://github.com/Microsoft/Reporting-Services/tree/master/CustomSecuritySample2016) I had to add a machinekey element to the machine.config file located in  

> C:\Windows\Microsoft.NET\Framework64\v4.0.30319\Config

After that It works, but I receive an error message: 
![image](https://user-images.githubusercontent.com/37124448/39410147-f9b1d23e-4bb8-11e8-9786-074ea97319ba.png)


> `RSPortal!reportserverwebapp!RSPortal.exe!6!04/29/2018-14:09:19:: i INFO: Received request GET /api/v2.0/SafeGetSystemResourceContent%28type%3D%27UniversalBrand%27%2Ckey%3D%27logo%27%29 | RequestID = s_75a32377-3a83-4e83-93fa-be799ef9e0eb 
RSPortal!library!RSPortal.exe!c!04/29/2018-14:09:19:: e ERROR: Throwing Microsoft.ReportingServices.Diagnostics.Utilities.AccessDeniedException: , Microsoft.ReportingServices.Diagnostics.Utilities.AccessDeniedException: The permissions granted to user 'MY_USER_NAME' are insufficient for performing this operation.;
RSPortal!library!RSPortal.exe!b!04/29/2018-14:09:19:: e ERROR: Throwing Microsoft.ReportingServices.Diagnostics.Utilities.AccessDeniedException: , Microsoft.ReportingServices.Diagnostics.Utilities.AccessDeniedException: The permissions granted to user 'MY_USER_NAME' are insufficient for performing this operation.;`

**Comment by ganeshmahajan1985** [comment]
Hi @SLazaroc ,

did you updated the username in the section below -  It should be the username which you created from the new custom security UI. example - admin. 
I have created user "**admin**" and added it in <UserName> tag

```
<Security>
	<Extension Name="Forms" Type="Microsoft.Samples.ReportingServices.CustomSecurity.Authorization, Microsoft.Samples.ReportingServices.CustomSecurity" >
	<Configuration>
		<AdminConfiguration>
			<UserName>**username**</UserName>
		</AdminConfiguration>
	</Configuration>
	</Extension>
</Security>
```
