### ISSUE TITLE
PBIRS (March 2018 release) with custom authentication error

### ISSUE THREAD

**Issue by erosal84** [Microsoft/Reporting-Services#97]
I'm trying to configure the March, 2018 PBIRS release to use custom authentication. We have the October 2017 release working fine, but need to move to the latest version. 

I think I followed all of the instructions properly, including the generation of an AES/AES machine key that I've included in rsreportserver.config:

`<MachineKey ValidationKey="[myValidationKey]" DecryptionKey="[myDecryptionKey]" Validation="AES" Decryption="AES" />
`

But when I try to access the PBIRS portal, I get an HTTP 500 error and the RSPortal log reports the following error:

````
2018-06-20 16:33:17.4985|ERROR|5| 192.168.32.221: GET /browse/ - 0:00:00.0315727
Exception: System.Web.HttpException (0x80004005): Unable to validate data.
   at System.Web.Configuration.MachineKeySection.EncryptOrDecryptData(Boolean fEncrypt, Byte[] buf, Byte[] modifier, Int32 start, Int32 length, Boolean useValidationSymAlgo, Boolean useLegacyMode, IVType ivType, Boolean signData)
   at System.Web.Security.FormsAuthentication.Decrypt(String encryptedTicket)
   at Microsoft.BIServer.Owin.Common.Middleware.CustomAuthenticationMiddleware.CreateRequestContextFromCookie(IOwinContext context)
   at Microsoft.BIServer.Owin.Common.Middleware.CustomAuthenticationMiddleware.CreatePortalIdentity(IOwinContext context)
   at Microsoft.BIServer.Owin.Common.Middleware.CustomAuthenticationMiddleware.Invoke(IOwinContext context)
   at Microsoft.Owin.Security.Infrastructure.AuthenticationMiddleware`1.<Invoke>d__0.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.BIServer.Owin.Common.Middleware.RequestLoggingMiddleWare.<Invoke>d__2.MoveNext()| RequestID = s_8746993e-6fe4-4a0d-84d3-ff0d3256c9cc 
````
I notice that when the service starts, a machine key entry is being added to a couple of the config files, such as rsportal.config and web.config.  The key values match, but the formatting is different. Where my entry in rsreportserver.config capitalizes each word (MachineKey / ValidationKey), the generated entries in rsportal.config, etc. does it differently (machineKey / validationKey).  However, if I change my rsreportserver.config value to match the generated value in rsportal.config, no machine key entry gets generated and in fact, no rsportal log file gets written, and rather than an HTTP 500 error, I get an HTTP 503.

Any suggestions? This is all kinds of frustrating, and we really need to get the new PBIRS release up and running.

**Comment by erosal84** [comment]
I've narrowed down the issue, and have gotten the latest version of PBIRS to work with the default custom authentication, so I'm going to close this issue and submit another.
