### ISSUE TITLE
PBIRS (March 2018 release) with custom authentication error

### ISSUE THREAD

**Issue by erosal84** [Microsoft/Reporting-Services#98]
I'm trying to configure the March 2018 PBIRS release to use custom authentication. We have the October 2017 release working fine, but need to move to the latest version.  If I customize the March 2018 release with the default configuration as specified in the ReadMe.md, it works properly. I can register new users and log into the PBIRS server through the logon.aspx page.  However, our forms authentication requirements are a bit more complicated than that.

We are displaying embedded Power BI reports in our existing form-authenticated application, so rather than using the default PassThroughCookies specified for rsreportserver.config, we use the following:

	          `<PassThroughCookies>
	            <PassThroughCookie>.ASPXAUTH</PassThroughCookie>
	          </PassThroughCookies>`

Similarly, in web.config, instead of the "forms" configuration with "logon.aspx" and "sqlAuthCookie", we point to our application login:

      `<forms timeout="120" domain=".productiondomain.com" cookieless="UseCookies" enableCrossAppRedirects="true" name=".ASPXAUTH" loginUrl="http://formsLogin.productiondomain.com" />`

The server seems to start properly, with no errors in any of the log files -- until I attempt to access the PBIRS portal (https://pbirs.productiondomain.com/Reports).  The access attempt results in an HTTP 500 error on my browser, and the following error in the RSPortal log file:

```
2018-06-20 16:33:17.4985|ERROR|5| 192.168.32.221: GET /browse/ - 0:00:00.0315727
Exception: System.Web.HttpException (0x80004005): Unable to validate data.
   at System.Web.Configuration.MachineKeySection.EncryptOrDecryptData(Boolean fEncrypt, Byte[] buf, Byte[] modifier, Int32 start, Int32 length, Boolean useValidationSymAlgo, Boolean useLegacyMode, IVType ivType, Boolean signData)
   at System.Web.Security.FormsAuthentication.Decrypt(String encryptedTicket)
   at Microsoft.BIServer.Owin.Common.Middleware.CustomAuthenticationMiddleware.CreateRequestContextFromCookie(IOwinContext context)
   at Microsoft.BIServer.Owin.Common.Middleware.CustomAuthenticationMiddleware.CreatePortalIdentity(IOwinContext context)
   at Microsoft.BIServer.Owin.Common.Middleware.CustomAuthenticationMiddleware.Invoke(IOwinContext context)
   at Microsoft.Owin.Security.Infrastructure.AuthenticationMiddleware`1.<Invoke>d__0.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.BIServer.Owin.Common.Middleware.RequestLoggingMiddleWare.<Invoke>d__2.MoveNext()| RequestID = s_8746993e-6fe4-4a0d-84d3-ff0d3256c9cc
``` 
   
With the October 2017 release of PBIRS and the old version of the CustomSecuritySample, things worked just fine. Using the March 2018 release of PBIRS with either the old version or current version of CustomSecuritySample with our additional customizations fails.

**Comment by erosal84** [comment]
Problem solved -- I needed to make sure that the MachineKey value for PBIRS was the same as the one for our forms-authenticated application.

Whew!
